name: linopti
channels:
  - gurobi
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.16
  - arrow=1.3.0
  - astroid=2.14.2
  - asttokens=2.0.5
  - atomicwrites=1.4.0
  - attrs=24.3.0
  - autopep8=2.0.4
  - babel=2.16.0
  - backcall=0.2.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - black=24.10.0
  - blas=1.0
  - bleach=6.2.0
  - brotli-python=1.0.9
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - cffi=1.17.1
  - chardet=4.0.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.1
  - cookiecutter=2.6.0
  - cryptography=44.0.1
  - cycler=0.11.0
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.8
  - docstring-to-markdown=0.11
  - docutils=0.18.1
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - flake8=6.1.0
  - fonttools=4.55.3
  - freetype=2.12.1
  - gurobi=10.0.3
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.7
  - imagesize=1.4.1
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.0
  - inflection=0.5.1
  - intel-openmp=2023.1.0
  - intervaltree=3.1.0
  - ipykernel=6.29.5
  - ipython=8.15.0
  - isort=5.13.2
  - jaraco.classes=3.2.1
  - jedi=0.19.2
  - jellyfish=1.1.3
  - jinja2=3.1.6
  - jpeg=9e
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_pygments=0.3.0
  - keyring=24.3.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy-object-proxy=1.10.0
  - lcms2=2.16
  - lerc=3.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libpng=1.6.39
  - libpq=17.4
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.0
  - mistune=3.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - more-itertools=10.3.0
  - mypy_extensions=1.0.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy-base=1.26.4
  - numpydoc=1.7.0
  - openjpeg=2.5.2
  - openpyxl=3.0.10
  - openssl=3.0.16
  - packaging=24.2
  - pandas=2.1.4
  - pandoc=2.12
  - pandocfilters=1.5.0
  - paramiko=3.5.0
  - parso=0.8.4
  - pathspec=0.10.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=3.10.0
  - pluggy=1.5.0
  - ply=3.11
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.11.1
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=3.1.0
  - pygments=2.15.1
  - pylint=2.16.2
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.9.0
  - python-lsp-server-base=1.9.0
  - python-slugify=5.0.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytoolconfig=1.2.6
  - pywin32=308
  - pywin32-ctypes=0.2.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qdarkstyle=3.2.3
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.3.1
  - qtconsole=5.5.1
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - referencing=0.30.2
  - requests=2.32.3
  - rich=13.9.4
  - rope=1.12.0
  - rpds-py=0.22.3
  - rtree=1.0.1
  - setuptools=75.8.0
  - sip=6.7.12
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=7.3.7
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.10
  - spyder=5.5.0
  - spyder-kernels=2.5.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tabulate=0.9.0
  - tbb=2021.8.0
  - text-unidecode=1.3
  - textdistance=4.6.3
  - three-merge=0.1.1
  - tinycss2=1.4.0
  - tomli=2.0.1
  - tomlkit=0.13.2
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - ujson=5.10.0
  - unicodedata2=15.1.0
  - unidecode=1.3.8
  - urllib3=2.3.0
  - vc=14.2
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - watchdog=4.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - whatthepatch=1.0.2
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - wrapt=1.17.0
  - xz=5.6.4
  - yaml=0.2.5
  - yapf=0.40.2
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - bottleneck==1.3.6
      - click==8.1.3
      - cloudpickle==2.2.1
      - dask==2023.2.0
      - deprecation==2.1.0
      - fsspec==2023.1.0
      - linopy==0.3
      - locket==1.0.0
      - numpy==1.24.2
      - partd==1.3.0
      - pytz==2022.7.1
      - scipy==1.10.1
      - toolz==0.12.0
      - tqdm==4.64.1
      - xarray==2024.7.0